config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  root to: "users#index"
  resources :users
  resources :categories, only: [:index, :show, :new, :create] 
  resources :transacs, only: [:index, :show, :new, :create] 
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    return unless user.present?

    can :manage, Category, author_id: user.id
    can :manage, Transac, author_id: user.id

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :transacs

  validates :name, presence: true
  validates :name, length: { minimum: 3, maximum: 50 }
end

app/models/transac.rb
class Transac < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :categories

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, foreign_key: 'author_id'
  has_many :transacs, foreign_key: 'author_id'
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  # GET /categories or /categories.json
  def index
    @categories = Category.where(author: current_user)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @transacs = @category.transacs.order('created_at DESC')
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.author = current_user
    if @category.save
      redirect_to categories_url, notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/transacs_controller.rb
class TransacsController < ApplicationController
  before_action :authenticate_user!
  def index
    @transacs = Transac.all.where(author_id: current_user.id).order(created_at: :desc)
  end

  def show
    @transac = Transac.find_by(id: params[:id])
  end

  def new
    @transac = Transac.new
    @categories = Category.where(author: current_user)
    return unless params[:category_id]

    @category = Category.find(params[:category_id])
  end

  def create
    @transac = Transac.new(transac_params)
    @transac.author = current_user
    @category = Category.find(params[:transac][:category_id])
    @transac.categories << @category
    if @transac.save
      redirect_to category_url(params[:transac][:category_id]), notice: 'Transaction was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def transac_params
    params.require(:transac).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[index]
  def index
    return unless user_signed_in?

    redirect_to categories_path
  end

  # GET /users/1 or /users/1.json
  # def show
  # end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<%=link_to category_path(category), class: "category-item" do%> 
    <p class= "d-flex justify-content-start align-items-center">
      <img src="<%= category.icon %>" style = "width: 50px; height: 50px;">
      <strong><%= category.name.capitalize() %></strong>
    </p>
    <p>
      $<%= category.transacs.map{|s| s.amount}.sum %>
    </p>
    <%end%>

app/views/categories/index.html.erb
<section class="flex-column height-full">
<nav class="navbar-container justify-content-between">
  <div></div>
  <h5 class="white-color">CATEGORIES</h5>
  <%= button_to destroy_user_session_path, method: :delete, class:"login-button" do %>
  <i class="fa-solid fa-right-from-bracket" style="color: #ffffff;"></i>
  <% end %>
</nav>

<p class="text-align-center" style="color: green "><%= notice %></p>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>
<%= link_to new_category_path, class: "new-catagory-container" do %>
  <div>
    New Category
  </div>
<% end %>
</section>

app/views/categories/new.html.erb
<section class="flex-column height-full">
<nav class="navbar-container justify-content-between">
  <%=link_to categories_path do%>
  <i class="fa-sharp fa-solid fa-arrow-left white-color"></i>
  <%end%>
  <h5 class="white-color">ADD CATEGORIES</h5>
  <div></div>
</nav>
<%= form_with model: @category, url: categories_path, class: "new-category" do |form| %>
  <div>
    <% if @category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field first-field">
    <%= form.text_field :name, placeholder: "Category name"%>
  </div>

  <div class="field last-field">
    <%= form.text_field :icon, placeholder: "Link for icon" %>
  </div>
  </div>

  <div class="save-catagory">
    <%= form.submit "Save", class: "new-catagory-container" %>
  </div>
<% end %>
</section>

app/views/categories/show.html.erb
<section class="flex-column height-full">
<nav class="navbar-container justify-content-between">
  <%=link_to categories_path do%>
  <i class="fa-sharp fa-solid fa-arrow-left white-color"></i>
  <%end%>
  <h5 class="white-color">Transaction</h5>
  <%= button_to destroy_user_session_path, method: :delete, class:"login-button" do %>
  <i class="fa-solid fa-right-from-bracket" style="color: #ffffff;"></i>
  <% end %>
</nav>

<p class= "text-align-center" style="color: green"><%= notice %></p>

<%= render @category %>

<div class= "purchases-list">
<% @transacs.each do |transac|%>
<div class= "category-item">
  <p><%= transac.name %></p>
  <p>$<%= transac.amount %></p>
</div>
<%end%>
</div>
<%= link_to new_transac_path(:category_id => @category.id), class: "new-catagory-container" do %>
  <div>
    New Transaction
  </div>
<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"/>
    <link href="http://fonts.cdnfonts.com/css/proxima-nova-2" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/f52b1d73e5.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container", style="min-height: 84vh;">

    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-center text-lg-start fixed-bottom">
  <!-- Copyright -->
  <div class="text-center p-3t text-light ">
    © 2023 Copyright <br>
    <a class="text-blue text-decoration-none" href="https://github.com/degisew">Harshita Jain</a> 
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark custom-nav">
  <div class="container-fluid">
  <%= link_to 'Budget App', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to 'Categories', categories_url, class: 'nav-link'%>
        </li>
       
      </ul>

    </div>
    <li class="d-flex justify-content-end ml-auto">
        <% if user_signed_in? %>
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-light  text-end', data: { turbo: false } %>
        <% else %>
        <%= button_to 'Sign In', new_user_session_path, class: 'nav-link btn btn-light text-end'%>
        <% end%>
        </li>
  </div>
</nav>

app/views/transacs/new.html.erb
<section class="flex-column height-full">
<nav class="navbar-container justify-content-between">
  <%=link_to :back, class: "back" do%>
  <i class="fa-sharp fa-solid fa-arrow-left white-color"></i>
  <%end%>
  <h5 class="white-color">ADD TRANSACTION</h5>
  <div></div>
</nav>

<%= form_with model: @transac, url: transacs_path, method: :post, class: "new-category" do |form| %>
  <div>
  <% if @transac.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@transac.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% @transac.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field first-field">
    <%= form.text_field :name, placeholder: "Transaction Name"%>
  </div>

  <div class= "field">
    <%= form.number_field :amount, placeholder: "Amount" %>
  </div>

  <div class = "field last-field">
  <%if @category %>
    <%= form.select :category_id, @categories.collect { |c| [c.name, c.id] }, { selected: @category.id } %>
  <%else%>
    <%= form.select :category_id, @categories.collect { |c| [c.name, c.id] } %>
  <%end%>
  </div>
  
  </div>
  <div class="save-catagory">
    <%= form.submit "Save", class: "new-catagory-container" %>
  </div>
<% end %>
</section>

app/views/users/index.html.erb
<p class="text-align-center"><%= notice %></p>
<section class='home-container'>
<h1>Budget App</h1>

<div class='login-signup-container'>
<%=link_to "Log in", new_user_session_path, class: 'blue-button'%>
<%=link_to "Sign up", new_user_registration_path, class: 'grey-button'%>


</div>

</section>

app/views/users/show.html.erb
<p class="text-align-center"><%= notice %></p>
<section class='home-container'>
<h1>Budget App</h1>

<div class='login-signup-container'>
<%=link_to "Log in", new_user_session_path, class: 'blue-button'%>
<%=link_to "Sign up", new_user_registration_path, class: 'grey-button'%>


</div>

</section>